- Remove setup script and Implement db_schema
maurisource/mageship pull request #7
Opened 2024-02-29 19:02 UTC by npatelmaurisource

2024-02-29 20:40 UTC, maurisource requested changes
When you update module version, you need to update composer.json file as well with same version

2024-03-01 17:07 UTC, npatelmaurisource commented
Ok

2024-03-01 17:08 UTC, npatelmaurisource commented
Done

2024-03-12 18:30 UTC, maurisource approved these changes

2024-03-12 18:30 UTC, merged